jamescooke/flake8-aaa

flake8_aaa/function.py
setup.cfg
tests/function/test_check.py
tests/function/test_parse.py
tests/test_run.py
tox.ini

Allow `pytest.raises` in Assert blocks

---

CHANGELOG.rst
README.rst
flake8_aaa/__about__.py
tests/test_run.py

Bump v0.2.0

---

CHANGELOG.rst
flake8_aaa/arrange_block.py
flake8_aaa/assert_block.py
flake8_aaa/function.py
tests/arrange_block/test_add_node.py
tests/function/conftest.py
tests/function/test_check_act_arrange_spacing.py
tests/function/test_check_act_assert_spacing.py
tests/function/test_check_all.py
tests/function/test_load_arrange_block.py
tests/function/test_load_assert_block.py
tests/test_run.py

Add AAA04 rule (space between Act and Assert)

---

CHANGELOG.rst
flake8_aaa/act_block.py
flake8_aaa/exceptions.py
flake8_aaa/function.py
tests/act_block/test_build.py
tests/function/test_load_act_block.py

Handle context managers

---

README.rst
docs/discovery.rst
docs/index.rst
docs/rules.rst

Mainly:
* Expansion on information about test discovery.
* Addition of "note" on reading rules in context of pattern description as a result of [feedback](http://lists.idyll.org/pipermail/testing-in-python/2018-September/007219.html).

Documentation improvements

---

docs/commands.rst
docs/index.rst

I added some initial documentation for the command-comments.
However there should be some examples (and maybe there are some other commands?)

added initial documentation for commands (for #44)

---

.github/ISSUE_TEMPLATE/bug_report.md
CODE_OF_CONDUCT.md

* Create basic issue template.
* Add standard Code of Conduct.

Add GitHub community docs

---

Makefile
docs/commands.rst
examples/good/noqa/test_01.py
examples/good/noqa/test_03.py
examples/good/noqa/test_04.py
flake8_aaa/checker.py
flake8_aaa/command_line.py
flake8_aaa/helpers.py
tests/helpers/test_find_test_functions.py
tox.ini

Make command line respect NOQA

---

.travis.yml
CHANGELOG.rst
README.rst
requirements/base.txt
requirements/dev.txt
requirements/test.txt
setup.py
src/flake8_aaa/line_markers.py
tests/line_markers/test_check_act_assert_spacing.py
tox.ini

Update python versions supported

---

Makefile

Needed to point at `/src` dir.

Fix on_master check

---

CHANGELOG.rst
docs/discovery.rst
docs/rules.rst
examples/bad/bad_expected.out
examples/bad/test_aaa05.py
examples/good/test_comments_aaa05.py
src/flake8_aaa/function.py
src/flake8_aaa/helpers.py
src/flake8_aaa/line_markers.py
tests/function/test_mark_bl.py
tests/helpers/test_find_stringy_lines.py
tests/line_markers/test_check_act_assert_spacing.py
tests/line_markers/test_check_arrange_act_spacing.py
tests/line_markers/test_check_blank_lines.py
tests/line_markers/test_update.py
tox.ini

Fixes #66 
Checks for blank lines in tests' definition, arrange, act and assert blocks.

Add AAA05 blank line in block

---

README.rst

This is the IMO most intuitive way of showing how flake8-aaa looks like. However some examples might be helpful for beginners. On the other hand I think a link to the examples should be in the TL;DR instead, to keep it short.

fixed misleading TL;DR related to #103

---

CHANGELOG.rst
README.rst
docs/compatibility.rst
docs/index.rst
docs/release_checklist.rst

Add docs for compatibility

---

.gitignore
CHANGELOG.rst
Makefile
docs/commands.rst
examples/bad/bad_expected.out
examples/bad/flake8_expected.out
examples/bad/test_noqa_flake8.py
examples/good/black/noqa/test_01.py
examples/good/black/noqa/test_02.py
examples/good/black/noqa/test_03.py
examples/good/black/noqa/test_04.py
examples/good/black/noqa/test_cmd.py
examples/good/noqa/test_01.py
examples/good/noqa/test_02.py
examples/good/noqa/test_03.py
examples/good/noqa/test_04.py
examples/good/noqa/test_cmd.py
requirements/base.txt
requirements/dev.txt
requirements/lintexamples.txt
requirements/test.txt
setup.cfg
src/flake8_aaa/multi_node_block.py

Improve NOQA testing and docs

---

.travis.yml
CHANGELOG.rst
README.rst
docs/compatibility.rst
requirements/base.txt
requirements/dev.txt
requirements/lintexamples.txt
requirements/test.txt
setup.py
src/flake8_aaa/function.py
tests/checker/test_load.py
tests/function/fixtures/test_first_node_with_tokens.py
tests/function/fixtures/test_function.py
tests/function/test_init.py
tox.ini

Add python 3.8 support

---

CHANGELOG.rst
setup.cfg
src/flake8_aaa/helpers.py
tests/helpers/test_first_non_blank_char.py
tests/helpers/test_is_test_file.py
tests/line_markers/test_check_act_assert_spacing.py
tests/line_markers/test_check_arrange_act_spacing.py
tox.ini

Remove doctest

---

CHANGELOG.rst
examples/bad/bad_expected.out
examples/bad/test.py
examples/bad/tests.py
requirements/dev.txt
requirements/test.txt
src/flake8_aaa/helpers.py
tests/helpers/test_is_test_file.py

Add simple filenames to test file pattern

---

CHANGELOG.rst
README.rst
docs/commands.rst
docs/compatibility.rst
docs/index.rst
docs/release_checklist.rst

Improve compatibility and release checklist docs

---

docs/discovery.rst

Improve docs on test discovery

---

CHANGELOG.rst
src/flake8_aaa/helpers.py

Fix deprecation warning in AST in Python 3.8

---

CHANGELOG.rst
src/flake8_aaa/__about__.py

https://github.com/jamescooke/flake8-aaa/milestone/3

Bump to version 0.11.0

---

Makefile
setup.cfg

Fix isort config

---

CHANGELOG.rst
examples/good/test_comments.py
src/flake8_aaa/act_node.py
tests/function/test_load_act_node.py

Add case insensitive matching for "# act" search

---

README.rst

Add link to Pytest's docs from README

---

.github/workflows/build.yml
CHANGELOG.rst
README.rst
setup.py
tox.ini

Add explicit support for Python 3.9

---

README.rst

See https://github.com/badges/shields/issues/8671

Update Shield URL to get correct status

---

.github/workflows/build.yml
CHANGELOG.rst
setup.py
tox.ini

Add explicit support for Python 3.11

---

CHANGELOG.rst
docs/error_codes/AAA05-blank-line-in-block.rst
docs/error_codes/AAA06-comment-in-act-block.rst
examples/bad/bad_expected.out
examples/bad/test_aaa05.py
examples/bad/test_aaa06.py
tox.ini

* Hash-comment resolution doc added for AAA06. Fixes #193 
* Code examples added for AAA05: #149 
* AAA05 and AAA06 bad examples upgraded.

Add documentation for AAA06 hash-comment resolution, improve examples

---

CHANGELOG.rst
README.rst
docs/compatibility.rst
docs/discovery.rst
docs/error_codes/AAA01-no-act-block-found-in-test.rst
docs/error_codes/AAA03-expected-1-blank-line-before-act-block.rst
docs/error_codes/AAA06-comment-in-act-block.rst
docs/options.rst
examples/README.rst

Add docs on Large style Act blocks

---

CHANGELOG.rst
README.rst
docs/compatibility.rst
src/flake8_aaa/__about__.py

Bump to 0.15.0
